[config]
schemaVersion = "0.0.1"

[package]
namespace = "Yokai"
name = "yokai"
versionNumber = "1.0.5"
description = "Yokai Clan"
websiteUrl = "https://github.com/fohnjarmery/Yokai"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
MT2-Trainworks_Reloaded = "0.7.1"
Conductor-Conductor = "0.4.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./"

[[build.copy]]
source = "./plugin_build"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = [ "monster-train-2" ]


